# -*- coding: utf-8 -*-
"""tugas_kelompok6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B0dkEZapXV3ObZ9sLuSfwy0soCqXN9lK
"""

# ==============================================================================
# IMPORT LIBRARY & SETUP ENVIRONMENT
# ==============================================================================
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import statsmodels.api as sm
from scipy import stats
from statsmodels.stats.outliers_influence import variance_inflation_factor

# Konfigurasi visualisasi standar publikasi
sns.set_theme(style="whitegrid", palette="muted")
plt.rcParams["figure.figsize"] = (10, 6)


# ==============================================================================
# TAHAP 1: PROBLEM DEFINITION
# ==============================================================================
print("="*60)
print("TAHAP 1: PROBLEM DEFINITION")
print("="*60)
print("""
Rumusan Masalah:
1. Bagaimana karakteristik persebaran penduduk usia sekolah, luas wilayah, dan
   jumlah sekolah di Indonesia?
2. Apakah terdapat hubungan linear yang kuat antara jumlah penduduk usia sekolah
   dan luas wilayah terhadap jumlah sekolah?
3. Faktor mana yang memberikan kontribusi paling signifikan terhadap
   pembangunan sekolah baru?

Hipotesis:
H0: Tidak ada pengaruh signifikan antara penduduk usia sekolah dan luas wilayah
    terhadap jumlah sekolah.
H1: Terdapat pengaruh positif dan signifikan dari penduduk usia sekolah dan
    luas wilayah terhadap jumlah sekolah.
""")


# ==============================================================================
# TAHAP 2: DATA COLLECTION
# ==============================================================================
print("\n" + "="*60)
print("TAHAP 2: DATA COLLECTION")
print("="*60)

# --- SIMULASI DATASET ---
np.random.seed(42)
n_prov = 38
total_pop = np.random.normal(3000000, 1000000, n_prov)
school_age = total_pop * np.random.uniform(0.18, 0.22, n_prov)
area = np.random.normal(50000, 15000, n_prov)

# Persamaan untuk Y (Jumlah Sekolah)
schools = (school_age * 0.003) + (area * 0.01) + np.random.normal(0, 100, n_prov)

df = pd.DataFrame({
    "provinsi": [f"Provinsi_{i+1}" for i in range(n_prov)],
    "penduduk_usia_sekolah": school_age.astype(int),  # X1
    "total_penduduk": total_pop.astype(int),          # X2
    "luas_wilayah": area.astype(int),                 # X3
    "jumlah_sekolah": schools.astype(int),            # Y
})

print("=== INSPEKSI AWAL DATA ===")
print(f"Dimensi Dataset: {df.shape[0]} Baris (Provinsi), {df.shape[1]} Kolom")
display(df.head())


# ==============================================================================
# TAHAP 3: DATA CLEANING
# ==============================================================================
print("\n" + "="*60)
print("TAHAP 3: DATA CLEANING")
print("="*60)

print("=== Pengecekan Missing Values ===")
print(df.isnull().sum())

print("\n=== Pengecekan Duplikasi Data ===")
print(f"Jumlah baris duplikat: {df.duplicated().sum()}")

# Validasi logis: Data numerik tidak boleh bernilai negatif
kolom_numerik = ["penduduk_usia_sekolah", "total_penduduk", "luas_wilayah", "jumlah_sekolah"]
for col in kolom_numerik:
    df = df[df[col] >= 0]

print(f"\nDimensi Dataset setelah cleaning: {df.shape[0]} Baris")


# ==============================================================================
# TAHAP 4: EXPLORATORY DATA ANALYSIS (EDA)
# ==============================================================================
print("\n" + "="*60)
print("TAHAP 4: EXPLORATORY DATA ANALYSIS")
print("="*60)

print("=== TABEL STATISTIK DESKRIPTIF NASIONAL ===")
deskriptif = df[kolom_numerik].describe().T[["mean", "std", "min", "50%", "max"]]
deskriptif.columns = ["Rata-rata", "Std Deviasi", "Minimum", "Median", "Maksimum"]
display(deskriptif)

# Visualisasi Matriks Korelasi
corr_matrix = df[kolom_numerik].corr(method="pearson")

plt.figure(figsize=(8, 6))
sns.heatmap(
    corr_matrix,
    annot=True,
    fmt=".2f",
    cmap="Blues",
    cbar=True,
    annot_kws={"size": 12},
)
plt.title("Matriks Korelasi Pearson Antar Variabel", fontsize=14, pad=15, fontweight="bold")
plt.show()

# Mencetak kesimpulan langsung setelah grafik dirender
print("""
[KESIMPULAN ANALISIS MATRIKS KORELASI]
1. Multikolinieritas Indikatif: Terdapat korelasi yang sangat tinggi (mendekati 1.00)
   antara 'total_penduduk' dan 'penduduk_usia_sekolah'. Hal ini rasional karena usia sekolah
   adalah subset dari total penduduk. Memasukkan keduanya sekaligus dalam regresi
   akan memicu kolinieritas.
2. Korelasi Target: 'penduduk_usia_sekolah' berkorelasi positif yang sangat kuat
   dengan 'jumlah_sekolah', mengonfirmasi asumsi awal bahwa demografi usia spesifik
   berjalan beriringan dengan jumlah fasilitas pendidikan.
""")


# ==============================================================================
# TAHAP 5: STATISTICAL MODELING
# ==============================================================================
print("\n" + "="*60)
print("TAHAP 5: STATISTICAL MODELING")
print("="*60)

# Uji VIF
X_check = df[["penduduk_usia_sekolah", "total_penduduk", "luas_wilayah"]]
X_check_const = sm.add_constant(X_check)

vif_table = pd.DataFrame()
vif_table["Variabel Independen"] = X_check_const.columns
vif_table["Nilai VIF"] = [
    variance_inflation_factor(X_check_const.values, i)
    for i in range(X_check_const.shape[1])
]

print("=== UJI ASUMSI MULTIKOLINIERITAS (VIF) ===")
display(vif_table)
print("-> Keputusan Analitik: Variabel X2 (total_penduduk) akan di-drop pada pemodelan\n"
      "   karena memiliki nilai VIF sangat tinggi (redundant dengan X1).\n")

# Model Regresi OLS Final
X_final = df[["penduduk_usia_sekolah", "luas_wilayah"]]
X_final = sm.add_constant(X_final)
y = df["jumlah_sekolah"]

model_regresi = sm.OLS(y, X_final).fit()
print("=== RINGKASAN MODEL REGRESI (OLS) ===")
print(model_regresi.summary())

# Plot Residual
df["prediksi"] = model_regresi.predict(X_final)
df["residual"] = y - df["prediksi"]

plt.figure(figsize=(9, 5))
sns.scatterplot(x=df["prediksi"], y=df["residual"], color="red", s=70, alpha=0.7)
plt.axhline(y=0, color="black", linestyle="--")
plt.title("Plot Residual vs Fitted Values (Uji Homoskedastisitas)", fontweight="bold")
plt.xlabel("Nilai Prediksi Jumlah Sekolah")
plt.ylabel("Residual (Error)")
plt.show()

# Mencetak kesimpulan langsung setelah grafik dirender
print("""
[KESIMPULAN GRAFIK RESIDUAL VS FITTED VALUES]
1. Asumsi Homoskedastisitas Terpenuhi: Titik-titik residual tersebar acak di atas
   dan di bawah garis nol tanpa membentuk pola tertentu (tidak mekar seperti terompet).
2. Makna: Varians galat dari model konstan. Model regresi OLS stabil, seimbang,
   dan valid untuk digunakan memprediksi kebutuhan infrastruktur pendidikan.
""")


# ==============================================================================
# TAHAP 6: INTERPRET & COMMUNICATE
# ==============================================================================
print("\n" + "="*60)
print("TAHAP 6: INTERPRET & COMMUNICATE")
print("="*60)
print("""
[INSIGHT & REKOMENDASI FINAL]

1. Validasi Hipotesis:
   Model regresi berhasil menolak H0 dan mengonfirmasi H1. Penduduk usia sekolah
   dan luas wilayah secara simultan berpengaruh signifikan terhadap sebaran
   jumlah sekolah di Indonesia.

2. Insight Pemodelan:
   Koefisien regresi menunjukkan bahwa pertumbuhan populasi usia sekolah memiliki
   daya dorong yang jauh lebih absolut terhadap penambahan sekolah baru dibandingkan
   ukuran geografis wilayah tersebut.

3. Rekomendasi Kebijakan Publik:
   Dalam mengalokasikan Dana Alokasi Khusus (DAK) Pendidikan, pemerintah harus:
   - Menjadikan tren demografi usia sekolah (bukan sekadar rasio penduduk umum)
     sebagai bobot utama distribusi anggaran.
   - Menggunakan faktor 'luas wilayah' murni sebagai penyeimbang guna mencegah
     terjadinya blank-spot aksesibilitas pendidikan di provinsi yang sangat luas.

4. Keterbatasan & Saran Eksplorasi:
   Penelitian ini belum mengontrol aspek fiskal daerah (contoh: APBD) dan
   tipografi geografis (kepulauan vs kontinental). Peneliti selanjutnya direkomendasikan
   menyertakan variabel ekonomi makro untuk meningkatkan akurasi R-squared model.
""")