# -*- coding: utf-8 -*-
"""project_tugas_akhir_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lXtIs7jQ7vYTjGTUtcwLQZn42fwB1akj
"""
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import pearsonr, shapiro
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.stats.diagnostic import het_breuschpagan

sns.set_style("whitegrid")

# ==============================================================================
# INFORMASI PROJECT
# ==============================================================================

print("="*80)
print("ANALISIS HUBUNGAN JUMLAH PENDUDUK USIA SEKOLAH")
print("DENGAN PERSEBARAN SEKOLAH DI INDONESIA")
print("="*80)

print("\nMata Kuliah : Analisis Data Statistik")
print("Project Akhir Kelompok")

print("\nAnggota Kelompok")
print("-"*80)
print("1. Fariz Firmansyah                (0102525005)")
print("2. Sayid Muhammad Al Husain        (0102525018)")
print("3. Muhammad Farrel Inzaghi Santoso (0102525023)")
print("4. Azzindan Zulvan                 (0102525701)")
print("-"*80)

# ==============================================================================
# MEMBACA DATA
# ==============================================================================

df = pd.read_csv("complete_data.csv")

print("="*60)
print("DATASET AWAL")
print("="*60)

print(df.head())
print(df.info())
